/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_a1c55d7e (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/gvqwvuqeenkusdayosty/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a1c55d7e").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Try to create a key only if it does not already exist.
export const setIfNotExists = async (key: string, value: any): Promise<boolean> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a1c55d7e").insert({
    key,
    value,
  });

  if (!error) {
    return true;
  }

  if (typeof error.code === 'string' && error.code === '23505') {
    return false;
  }

  throw new Error(error.message);
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_a1c55d7e").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a1c55d7e").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Delete a key only when a JSON field matches an expected value.
export const delIfJsonFieldMatches = async (
  key: string,
  field: string,
  expectedValue: string,
): Promise<boolean> => {
  const supabase = client()
  const { data, error } = await supabase
    .from("kv_store_a1c55d7e")
    .delete()
    .eq("key", key)
    .filter(`value->>${field}`, 'eq', expectedValue)
    .select('key');

  if (error) {
    throw new Error(error.message);
  }

  return Array.isArray(data) && data.length > 0;
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a1c55d7e").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_a1c55d7e").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_a1c55d7e").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const rows = await getEntriesByPrefix(prefix);
  return rows.map((row) => row.value);
};

// Search for key-value pairs by prefix and preserve the matched keys.
export const getEntriesByPrefix = async (prefix: string): Promise<Array<{ key: string; value: any }>> => {
  const supabase = client()
  const rows: Array<{ key: string; value: any }> = [];
  const pageSize = 1000;
  let from = 0;

  while (true) {
    const to = from + pageSize - 1;
    const { data, error } = await supabase
      .from("kv_store_a1c55d7e")
      .select("key, value")
      .like("key", prefix + "%")
      .range(from, to);

    if (error) {
      throw new Error(error.message);
    }

    const batch = data ?? [];
    rows.push(...batch);
    if (batch.length < pageSize) {
      break;
    }

    from += pageSize;
  }
  }

  return rows;
};